### ISSUE TITLE
Convert json simple to gson in Updater

### ISSUE THREAD

**Issue by haveric** [haveric/VehicleStorage#1]
Gson is the new standard coming with the server and json simple is likely to disappear in the near future, so we should switch over to gson when possible.

**Comment by JoelLau** [comment]
@haveric if its not urgent, I should be able to get it up for you doing the week for hacktoberfest

**Comment by haveric** [comment]
It's not very urgent, so feel free whenever you have time.

**Comment by haveric** [comment]
This has been fixed, but as I said in the pull request, I'm sorry for not realizing it was a different user creating the pull request and will do my best to assign users going forward so this doesn't happen again.
